language: node_js
sudo: true
dist: trusty
before_script:
  - npm install -g bower web-component-tester
  - bower install
env:
  global:
    - CXX=g++-4.8
branches:
  only: 
    - master
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run -s '-screen 0 1280x800x24' wct --skip-plugin sauce
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi' 